version: '3'
services:
  app:
      build: .
      container_name: app
      env_file:
        - .env
      volumes:
        - .:/var/www/html
  nginx:
      build:
        context: .
        dockerfile: Dockerfile-nginx
      depends_on:
        - app
      ports:
        - 80:80
      volumes:
        - .:/var/www/html